### ISSUE TITLE
pd-icon does not load reliable

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#134] opened 2022-03-16 12:14 UTC
In our application context, the icons within `pd-icon` do not load reliable. For example we have the following list component, where only the first trash bin gets loaded but the trash bin icons in the line elements below do not load.
<img width="350" alt="problem" src="https://user-images.githubusercontent.com/77280472/158578894-9422f8f9-d3ae-42ea-b8b5-8644173c7902.png">

Comparing the HTML code of the first icon with the second one (e.g. the marked red box), we see a clear difference. The SVG is missing in the second item and also in and all items further below.
```js
<!-- THE FIRST TRASH ICON THAT WORKS -->
<div class="cp-icon-link" data-testid="delete-item-button" data-v-553e5241="" data-v-9ce87a8e="">
    <span class="cp-icon-link__icon" data-v-553e5241="">
        <pd-icon data-v-9ce87a8e="" data-v-553e5241-s="" role="img" class="hydrated" style="font-size: 2.2rem;">
            <div class="pd-icon-inner">
                <svg xmlns="http://www.w3.org/2000/svg" width="38" height="38" viewBox="0 0 38 38">
                    <path d="..." transform="translate(2 3)"></path>
                </svg>
            </div>
        </pd-icon>
    </span>
    <!---->
</div>

<!-- THE OTHER TRASH ICONS THAT ARE NOT SHOWN -->
<div class="cp-icon-link" data-testid="delete-item-button" data-v-553e5241="" data-v-9ce87a8e="">
    <span class="cp-icon-link__icon" data-v-553e5241="">
        <pd-icon data-v-9ce87a8e="" data-v-553e5241-s="" role="img" class="hydrated">
            <div class="pd-icon-inner"></div>
        </pd-icon>
    </span>
    <!---->
</div>
```

We can imagine some unintentional behaviour here with the caching for slower asynchronous requests. 
Maybe here https://github.com/Lambda-IT/parlamentsdienste-components/blob/master/src/components/pd-icon/pd-icon.tsx#L108 or when the wrapperElement is determined here https://github.com/Lambda-IT/parlamentsdienste-components/blob/master/src/components/pd-icon/pd-icon.tsx#L143 something doesn't work as expected and the subsequent icons are not loaded properly.

Maybe a helpful observation we made in this context: This problem seems to occur only for icons that come from elements that were made visible at a later point by the visibility rules from Vue (e.g. using a `v-if="isIconShown"`).

**Comment by thomasschneiter** [comment] 2022-04-13 07:59
This issue might be solved with #142

**Comment by CuriaPLUS** [comment] 2022-04-21 05:11
We've checked with [v2.3.0](https://github.com/Lambda-IT/parlamentsdienste-components/releases/tag/v2.3.0) in our application context and we are still experiencing the issue.

**Comment by thomasschneiter** [comment] 2022-04-25 13:09
@CuriaPLUS can you try to set `lazy` to false in this case? If it's still happening we could rule out the intersection observer as a problem that is used to lazy load icons.

**Comment by thomasschneiter** [comment] 2022-07-11 13:25
@CuriaPLUS I've created a new beta release which uses a different approach to loading the svg icons. 
Each icon now has it's own component that inlines the svg during the build. This means that no external assets have to be loaded anymore. 
The icon components are wrapped into the existing `<pd-icon>` component and use the same attributes as before. This means that no change is necessary to use them. 

**Be aware that:**
- With this change you cannot load your own svg files as `pd-icon` using the `src` attribute as the icon component doesn't load from files at runtime anymore. You'll need to use your own framework specific solution to load custom icons if you need them. Check the changelog for Breaking changes!

Can you check if this solves the issues with icons not loading reliably?

**Comment by CuriaPLUS** [comment] 2022-08-12 13:29
Dies löst unserer Probleme leider nicht. Wir haben das Problem noch weiter untersucht und einen Bug in VueJS gefunden (im Zusammenhang mit StencilJS). Wir haben evtl einen Möglichkeit dies zu fixen aber dies müsste wohl auf eurer Seite passieren -> meldet euch und wir setzten ein Meeting auf damit wir dies zusammen beheben können.

**Comment by FGrissmer** [comment] 2023-05-10 15:11
Hi

We have experienced this problem too. We have a list of lets say 25 items with icons where 5 are visible, 20 aren't. We delete one of the visible ones, reload the table, and the rest of the items move up the list, now we have 4 visible icons, 20 not loaded icons (that don't load when the viewport moves over them) and on loaded icon at the end of the list.

I suspect there is a problem with the IntersectionObserver, that either does not fire or fires on an element that doesn't exist anymore. When vue implements the changes of the model into the view the 20 not loaded items get into an invalid state.

We can not set the lazy parameter of these icons, because one of these icons is in a pd-menu element whose (three point) menu header icon lazy attribute we can't control.

Greetings

**Comment by tom-wenger** [comment] 2024-06-14 09:14
Sorry for the delay, i thought this issue was somehow solved, my fault. 
I once asked dominique if you can pass us a repo with a vue project and the component-library in it, so we can see the bug and inspect it, it was not possible at that point. is that still not possible?
because the problem for us is how to reproduce the issue...

**Comment by FGrissmer** [comment] 2024-07-11 15:39
Hi

We haven't tested it yet, but if this is fixed, this is fine for us and we consider this matter closed. We will incorporate this new version in the coming weeks.

**Comment by tom-wenger** [comment] 2024-08-20 07:07
I'll close this for now. If the problem occurs again, we can reopen it.

**Closed by tom-wenger** 2024-08-20 07:07 UTC
Labels: bug
